config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :fighters
  #get 'home/index'
  #root 'home#index'
  root 'fighters#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fighter.rb
class Fighter < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :fighters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /fighters or /fighters.json
  def index
    @fighters = Fighter.all
  end

  # GET /fighters/1 or /fighters/1.json
  def show
  end

  # GET /fighters/new
  def new
    @fighter = current_user.fighters.build
    #@fighter = Fighter.new
  end

  # GET /fighters/1/edit
  def edit
  end

  # POST /fighters or /fighters.json
  def create
    #@fighter = Fighter.new(fighter_params)
    @fighter = current_user.fighters.build(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to fighter_url(@fighter), notice: "Fighter was successfully created." }
        format.json { render :show, status: :created, location: @fighter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fighters/1 or /fighters/1.json
  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to fighter_url(@fighter), notice: "Fighter was successfully updated." }
        format.json { render :show, status: :ok, location: @fighter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1 or /fighters/1.json
  def destroy
    @fighter.destroy

    respond_to do |format|
      format.html { redirect_to fighters_url, notice: "Fighter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @fighter = current_user.fighters.find_by(id: params[ :id ])
    redirect_to fighters_path, notice: "Not Authorizes" if @fighter.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fighter
      @fighter = Fighter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fighter_params
      params.require(:fighter).permit(:first_name, :last_name, :phone, :style, :rank, :start_date, :last_payment, :notes, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fighters/_form.html.erb
<%= form_with(model: fighter) do |form| %>
  <% if fighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fighter.errors.count, "error") %> prohibited this fighter from being saved:</h2>

      <ul>
        <% fighter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label "Adı" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"Murat" %>
  </div>

  <div class="field form-group">
    <%= form.label "Soyadı" %>
    <%= form.text_field :last_name, class:"form-control",placeholder:"Gurbuz" %>
  </div>

  <div class="field form-group">
    <%= form.label "Telefon" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"0544 222 2222" %>
  </div>

  <div class="field form-group">
    <%= form.label "Dövüş Stili" %>
    <%= form.text_field :style, class:"form-control", placeholder:"Kick Boxing" %>
  </div>

  <div class="field form-group">
    <%= form.label "Kuşak" %>
    <%= form.text_field :rank, class:"form-control", placeholder:"Black Belt" %>
  </div>

  <div class="field form-group ">
    <%= form.label "Başlama Tarihi" %>
    <%= form.text_field :start_date, class:"form-control", placeholder:"01 Mayis 2020" %>
  </div>

  <div class="field form-group">
    <%= form.label "Son Ödeme" %>
    <%= form.text_field :last_payment, class:"form-control", placeholder:"13 Mayis 2022" %>
  </div>

  <div class="field form-group">
    <%= form.label "Notlar" %>
    <%= form.text_field :notes, class:"form-control", placeholder:"Turnuva hazirlik, borc vs.." %>
  </div>
  <div class="field form-group">
  <%= form.number_field :user_id, id: :fighter_user_id, class:"form-control", value:current_user.id, type: :hidden  %>
  </div>
  
  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<h1>Sporcuyu Düzenle</h1>
<%= render 'form', fighter: @fighter %>

<br>
<%= link_to 'Geri', fighters_path, class:"btn btn-dark" %>

<%= link_to 'Sil', @fighter, method: :delete, data: { confirm: 'Emin Misin?' },  type:"button", class:"btn btn-danger" %>

app/views/fighters/index.html.erb
<% if user_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
      <tr>
        <th>İsim</th>
        <th>Telefon</th>
        <th>Dövüş Stili</th>
        <th>Kuşak</th>
        <th>Başlama Tarihi</th>
        <th>Son Ödeme</th>
        <th>Notlar</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @fighters.each do |fighter| %>
        <% if fighter.user == current_user %>
        <tr>
          <td><%= link_to fighter.first_name + ' ' + fighter.last_name, fighter, class:"link-secondary" %> </td>
          <td><%= fighter.phone %></td>
          <td><%= fighter.style %></td>
          <td><%= fighter.rank %></td>
          <td><%= fighter.start_date %></td>
          <td><%= fighter.last_payment %></td>
          <td><%= fighter.notes %></td>
          <td><%= link_to 'Sil', fighter, method: :delete, data: { confirm: 'Emin Misin?' },  type:"button", class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Yeni Sporcu Ekle', new_fighter_path, class:"btn btn-secondary" %>
<% else %>
  <h1>Hector Spor Kulübü Sporcu Bilgi Sistemine Hoşgeldiniz</h1>
<br/><br/>
<p>Uygulamayı kullanmak için lütfen giriş yapınız<p>
<% end %>

app/views/fighters/new.html.erb
<div style="width: 36rem; margin:0 auto;">
 <h1>Sporcu Ekle</h1>
</div>

<div class="card" style="width: 36rem; margin:0 auto;">
  <div class="card-body">
    <%= render 'form', fighter: @fighter %>
    <br>
  </div>
</div>

<div style="width: 36rem; margin:0 auto;">
    <%= link_to 'Geri', fighters_path, class:"btn btn-secondary" %>
</div>

app/views/fighters/show.html.erb
<div class="jumbotron p-3 mb-2 bg-secondary text-white">
  <h1 class="display-4"><%= @fighter.first_name %> <%= @fighter.last_name %> </h1>
  <p class="lead"><%= @fighter.rank %>, <%= @fighter.style %> fighter. </p>
  <hr class="my-4">
  <p>Başlama Tarihi  <%= @fighter.start_date %></p>
  <p>Notlar: <%= @fighter.notes %> </p>
  <p>Son Ödeme: <%= @fighter.last_payment %></p>
  <br>
  <%= link_to 'Düzenle', edit_fighter_path(@fighter), class:"btn btn-light" %> 
  <%= link_to 'Geri', fighters_path, class:"btn btn-dark" %>
  <%= link_to 'Sil', @fighter, method: :delete, data: { confirm: 'Emin Misin?' },  type:"button", class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Hector Spor', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Hakkımızda', home_about_path, class:"nav-link" %>
        </li>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Çıkış Yap', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Profili Düzenle', edit_user_registration_path, class:"nav-link" %>
          <li class="nav-item">
            <%= link_to 'Yeni Sporcu Ekle', new_fighter_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sporcu Listesi', fighters_path, class:"nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
          <%= link_to 'Kayıt Ol', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Giriş Yap', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Ara" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Ara</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> Hakkımzıda </h1>
<br/> <br/>
Hector Spor Kulübü olarak Sporcularımız için Amaç ve hedeflerimiz: 

Farklı şekilerde temek motor becerileri edinmek ve fiziksel aktivite için uyaran almak,

Temel kendini koruma becerisi, güvenli ve sağlığı destekleyici egzersiz yolları öğrenmek,

Bir rekabet üzerinde durmaksızın, hem bireysel hem de işbirliği içinde çalışma becerilerini 
pratikleştirmek, 

Hilesiz bir oyun ruhu içinde kararlaştırılan yönergelere uymayı öğrenmek.

Kickboks Eğitim formlarının uygulamalarında;  Koşma, zıplama, atlama, itme, çekme, denge sağlama esneklik,  vurma ve savunma temel becerileri kazandırmak,

Neşeli fiziksel aktivitelerle; 

Temel motor becerilerini geliştirmeye devam etmek ve fiziksel aktivitenin belirli bir formunda 
beceri edinmek,
Huzuru(refahı) ve sağlığı korumada fiziksel aktivitenin önemini kavrayabilecek durumu 
gelmek,
Gözlemlemek ve fonksiyonel yeteneklerini geliştirmek,
Kickboks ve Muay Thai sporunda yeteneklerini geliştirmek ve elit sporcu becerileri edinmek,

Fiziksel aktivite ve müsabaka durumlarında güvenli ve uygun bir şekilde davranmayı öğrenmek,

Bağımsız veya bir takım ile hareket etmeyi öğrenmek, 

Hoşgörü çeşitliliği ve kendini kabul etmeyi öğrenmek, 

Eğitim programımızda ki  temel amaç ve hedeflerimizdir. 

@Hector Spor kulübü 
 Murat Gürbüz...

app/views/home/index.html.erb
<h1>Hector Spor Kulübü Sporcu Bilgi Sistemine Hoşgeldiniz</h1>
<br/><br/>
<p>Uygulamayı kullanmak için lütfen giriş yapınız<p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="tr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hector Spor Kulübü</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>